language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

script:
  - coverage run --omit=tests/*.py,/home/travis/virtualenv/* -m unittest
  - coveralls
